### PR TITLE
jgeorg fix for kernel 5.18

### PR DESCRIPTION
**Pull request by phako**
- Fix compilation with kernel >= 5.17
- Remove removed pci_set_*_dma calls

### CODE REVIEW

**Review by killenb — APPROVED** [review]

**Comment by phako** [comment]
Converted to draft due to unclear logic in the original code, asked for feedback on that

**Comment by phako** [comment]
The original code is weird, and also the current_mask return value is weird, checking the return value of dma_consistent is weird, reading on https://kernel.googlesource.com/pub/scm/linux/kernel/git/cmarinas/linux-aarch64/+/v2.6.29-rc4/Documentation/DMA-mapping.txt

**Review by killenb — APPROVED** [review]
Nice, there is a function in the new API which does exactly what we need :-)

**Comment by phako** [comment]
"new" in geological terms ... Kernel 4.5 is from 2016

**Pull request merged**
